/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LegalRouteImport } from './routes/_legal'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/_legal.terms'
import { Route as LegalRefundRouteImport } from './routes/_legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/_legal.privacy'
import { Route as LegalContactRouteImport } from './routes/_legal.contact'
import { Route as LegalAboutRouteImport } from './routes/_legal.about'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPostRouteImport } from './routes/_app.post'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppChatsRouteImport } from './routes/_app.chats'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppPaymentIdRouteImport } from './routes/_app.payment.$id'
import { Route as AppAssignmentIdRouteImport } from './routes/_app.assignment.$id'
import { Route as AppChatIdPeerRouteImport } from './routes/_app.chat.$id.$peer'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalContactRoute = LegalContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAboutRoute = LegalAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LegalRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPostRoute = AppPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentIdRoute = AppPaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentIdRoute = AppAssignmentIdRouteImport.update({
  id: '/assignment/$id',
  path: '/assignment/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdPeerRoute = AppChatIdPeerRouteImport.update({
  id: '/chat/$id/$peer',
  path: '/chat/$id/$peer',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/chats': typeof AppChatsRoute
  '/feed': typeof AppFeedRoute
  '/post': typeof AppPostRoute
  '/profile': typeof AppProfileRoute
  '/about': typeof LegalAboutRoute
  '/contact': typeof LegalContactRoute
  '/privacy': typeof LegalPrivacyRoute
  '/refund': typeof LegalRefundRoute
  '/terms': typeof LegalTermsRoute
  '/assignment/$id': typeof AppAssignmentIdRoute
  '/payment/$id': typeof AppPaymentIdRoute
  '/chat/$id/$peer': typeof AppChatIdPeerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/chats': typeof AppChatsRoute
  '/feed': typeof AppFeedRoute
  '/post': typeof AppPostRoute
  '/profile': typeof AppProfileRoute
  '/about': typeof LegalAboutRoute
  '/contact': typeof LegalContactRoute
  '/privacy': typeof LegalPrivacyRoute
  '/refund': typeof LegalRefundRoute
  '/terms': typeof LegalTermsRoute
  '/assignment/$id': typeof AppAssignmentIdRoute
  '/payment/$id': typeof AppPaymentIdRoute
  '/chat/$id/$peer': typeof AppChatIdPeerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_legal': typeof LegalRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/chats': typeof AppChatsRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/post': typeof AppPostRoute
  '/_app/profile': typeof AppProfileRoute
  '/_legal/about': typeof LegalAboutRoute
  '/_legal/contact': typeof LegalContactRoute
  '/_legal/privacy': typeof LegalPrivacyRoute
  '/_legal/refund': typeof LegalRefundRoute
  '/_legal/terms': typeof LegalTermsRoute
  '/_app/assignment/$id': typeof AppAssignmentIdRoute
  '/_app/payment/$id': typeof AppPaymentIdRoute
  '/_app/chat/$id/$peer': typeof AppChatIdPeerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/chats'
    | '/feed'
    | '/post'
    | '/profile'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/assignment/$id'
    | '/payment/$id'
    | '/chat/$id/$peer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/chats'
    | '/feed'
    | '/post'
    | '/profile'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/assignment/$id'
    | '/payment/$id'
    | '/chat/$id/$peer'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_legal'
    | '/auth'
    | '/reset-password'
    | '/_app/admin'
    | '/_app/chats'
    | '/_app/feed'
    | '/_app/post'
    | '/_app/profile'
    | '/_legal/about'
    | '/_legal/contact'
    | '/_legal/privacy'
    | '/_legal/refund'
    | '/_legal/terms'
    | '/_app/assignment/$id'
    | '/_app/payment/$id'
    | '/_app/chat/$id/$peer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LegalRoute: typeof LegalRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal/terms': {
      id: '/_legal/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/refund': {
      id: '/_legal/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/privacy': {
      id: '/_legal/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/contact': {
      id: '/_legal/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LegalContactRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/about': {
      id: '/_legal/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LegalAboutRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/post': {
      id: '/_app/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof AppPostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment/$id': {
      id: '/_app/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof AppPaymentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignment/$id': {
      id: '/_app/assignment/$id'
      path: '/assignment/$id'
      fullPath: '/assignment/$id'
      preLoaderRoute: typeof AppAssignmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$id/$peer': {
      id: '/_app/chat/$id/$peer'
      path: '/chat/$id/$peer'
      fullPath: '/chat/$id/$peer'
      preLoaderRoute: typeof AppChatIdPeerRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppChatsRoute: typeof AppChatsRoute
  AppFeedRoute: typeof AppFeedRoute
  AppPostRoute: typeof AppPostRoute
  AppProfileRoute: typeof AppProfileRoute
  AppAssignmentIdRoute: typeof AppAssignmentIdRoute
  AppPaymentIdRoute: typeof AppPaymentIdRoute
  AppChatIdPeerRoute: typeof AppChatIdPeerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppChatsRoute: AppChatsRoute,
  AppFeedRoute: AppFeedRoute,
  AppPostRoute: AppPostRoute,
  AppProfileRoute: AppProfileRoute,
  AppAssignmentIdRoute: AppAssignmentIdRoute,
  AppPaymentIdRoute: AppPaymentIdRoute,
  AppChatIdPeerRoute: AppChatIdPeerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LegalRouteChildren {
  LegalAboutRoute: typeof LegalAboutRoute
  LegalContactRoute: typeof LegalContactRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalAboutRoute: LegalAboutRoute,
  LegalContactRoute: LegalContactRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LegalRoute: LegalRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
